version: "3.9"
services:
  elixir:
    image: "elixir-npm"
    tty: "true"
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
        - /home/joao/dev/elixir:/src/elixir
  postgres:
    image: "postgres:latest"
    environment: 
        - "POSTGRES_PASSWORD=mysecretpassword"     
        - "PGDATA=/var/lib/postgresql/data/pgdata"
    ports:
        - "5432:5432"
    volumes: 
        - /custom/mount:/var/lib/postgresql/data
  postgres-client:
    image: "dpage/pgadmin4"
    environment: 
      - "PGADMIN_DEFAULT_EMAIL=user@domain.com"
      - "PGADMIN_DEFAULT_PASSWORD=ss"
    ports:
      - "8090:80"